spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

jwt:
  secret: MatorinFedorAndreevichBIB101200000
  expiration: 3600000